// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:dosador_concreto/my_classes.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CimAdapter());
    registerAdapter(DataAdapter());
    registerAdapter(MixAdapter());
    registerAdapter(MixsAdapter());
    registerAdapter(UnitAdapter());
    registerAdapter(UnitsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CimAdapter());
    registerAdapter(DataAdapter());
    registerAdapter(MixAdapter());
    registerAdapter(MixsAdapter());
    registerAdapter(UnitAdapter());
    registerAdapter(UnitsAdapter());
  }
}
